handle_dict = {
	'aoc' : 'tweets_aoc.json',
	'sensanders' : 'tweets_sensanders.json',
	'realdonaldtrump' : 'tweets_realdonaldtrump.json' ,
	'ewarren' : 'tweets_ewarren.json',
	'corybooker' : 'tweets_corybooker.json',
	'kamalaharris' : 'tweets_kamalaharris.json',
	'cnn' : 'tweets_cnn.json',
	'msnbc' : 'tweets_msnbc.json',
	'nbc' : 'tweets_nbc.json',
	'foxnews' : 'tweets_foxnews.json',
	'seanmcarroll' : 'tweets_seanmcarroll.json',
	'politico' : 'tweets_politico.json',
	'TheAtlantic' : 'tweets_theatlantic.json',
	'thehill' : 'tweets_thehill.json',
	'BreitbartNews' : 'tweets_breitbartnews.json',
	'maddow' : 'tweets_rachelmaddow.json',
	'CornelWest' : 'tweets_cornelwest.json',
	'nytimes' : 'tweets_nytimes.json',
	'NewYorker' : 'tweets_newyorker.json',
	'AJEnglish' : 'tweets_ajenglish.json',
	'MotherJones' : 'tweets_motherjones.json',
	'Salon' : 'tweets_salon.json',
	'ProPublica' : 'tweets_propublica.json',
	'PolitiFact' : 'tweets_politifact.json',
	'andersoncooper' : 'tweets_andersoncooper.json',
	'MMFlint' : 'tweets_michaelmoore.json',
	'ggreenwald' : 'tweets_ggreenwald.json',
	'seanhannity' : 'tweets_seanhannity.json', #only few tweets
	'IngrahamAngle' : 'tweets_lauraingraham.json',
	'greta' : 'tweets_gretavs.json',
	'benshapiro' : 'tweets_benshapiro.json',
	'EricRWeinstein' : 'tweets_ericweinstein.json',
	'joerogan' : 'tweets_joerogan.json',
	'ezraklein' : 'tweets_ezraklein.json',
	'jordanbpeterson' : 'tweets_jordanpeterson.json'
}